### PR TITLE
Browserify regression

### LINKED ISSUE #37: Regression: browserify fails
```
[14:01:10] Starting 'browserify'...
_stream_readable.js:540
    var ret = dest.write(chunk);
                   ^
TypeError: undefined is not a function
    at Producer.ondata (_stream_readable.js:540:20)
    at Producer.emit (events.js:107:17)
    at Producer.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

### PR DESCRIPTION
**Pull request by thorsteinsson**
This works, please let me know how I can improve the code. I don't really like adding vars to gulp.
Fixes #37.

### CODE REVIEW

**Comment by eirikurn** [comment]
I think we should either go more into globals and magic, or less. Now it's a strange cross between both where you never know what you should do.

I kinda like the node-yness of [gulp-starter](https://github.com/greypants/gulp-starter/blob/master/gulp/tasks/sass.js), where errorHandler is in its own util file which is required when needed. Though you probably only need it when a plugin is parsing developer code (jade, browserify and less) but maybe that's naive.

Also, I'm pretty sure gulp-uglify only works on buffered files, not streams. So you should buffer the file (or the plugin). Make sure `--prod` works.

**Comment by thorsteinsson** [comment]
Now we don't have any gulp globals and each task gets the config as a parameter.

I changed the prod checks to rather check the config for something more meaningful like debug and minify. Gulp and util are no longer passed to the tasks, each task requires what they need.

What do you think?

**Comment by eirikurn** [comment]
Did you test dev, prod, watch and less/browserify/jade errors? :)

**Comment by thorsteinsson** [comment]
Yep, all of that works.

**Comment by eirikurn** [comment]
Super! LGTM

lgtm

**Pull request merged**
